[project]
name = "aiagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.33.0",
    "matplotlib>=3.10.6",
    "numpy>=2.3.2",
    "pygame>=2.6.1",
    "python-dotenv>=1.1.1",
    "torch>=2.8.0",
]
